---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/grafana/config"
    owner: "{{ ansible_user }}"
    state: directory
    group: 101
    mode: 0775

- name: Copy the grafana.ini file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: "{{ docker_dir }}/grafana/config/grafana.ini"
    group: 101
    mode: 0775

- name: Create and run Grafana container
  community.docker.docker_container:
    image: "grafana/grafana-oss:latest"
    name: "grafana"
    pull: true
    user: "0:0"
    restart: true
    env:
      # "PUID": "1000"
      # "PGID": "1000"
      # "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/grafana/config/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ docker_dir }}/grafana/data:/var/lib/grafana"
    networks:
      - name: docker
    labels:
      traefik.http.routers.grafana.rule: Host(`grafana.{{ domain_name }}`)
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.tls: "true"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

      homepage.name: "Grafana"
      homepage.group: "Monitoring Tools"
      homepage.href: "http://grafana.{{ domain_name }}"
      homepage.description: "Dashboard-based Observability Tool"
      homepage.icon: "grafana.png"

    restart_policy: unless-stopped

- name: Add CNAME entry for grafana
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: grafana
