---
- name: Create and run Jellyfin container
  docker_container:
    image: "lscr.io/linuxserver/jellyfin"
    name: "jellyfin"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/jellyfin:/config"
      - "{{ media_dir }}/media:/data/media"
    network_mode: "host"
    labels:
      traefik.http.routers.jellyfin.entryPoints: https
      traefik.http.routers.traefik.rule: Host(`jellyfin.{{ domain }}`)
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadbalancer.server.url: "{{ ip }}:8096"
    restart_policy: unless-stopped

- name: Add CNAME entry for jellyfin
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: jellyfin
