---
- name: Create and run Jellyfin container
  community.docker.docker_container:
    image: "linuxserver/jellyfin:latest"
    name: "jellyfin"
    pull: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/jellyfin:/config"
      - "{{ media_dir }}/media:/data/media"
    networks:
      - name: docker
    labels:
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.{{ domain_name }}`)
      traefik.http.routers.jellyfin.entryPoints: https
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"

      homepage.name: "Jellyfin"
      homepage.group: "Main Apps"
      homepage.href: "http://jellyfin.{{ domain_name }}"
      homepage.description: "Unified media server"
      homepage.icon: "jellyfin.png"
      # homepage.widget.type: jellyfin
      # homepage.widget.url: "http://host.docker.internal:8096"
      # homepage.widget.key: ""
    restart_policy: unless-stopped

- name: Add CNAME entry for jellyfin
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: jellyfin
