---
- hosts: all
  name: Common Tasks
  roles:
    - role: common
      tags:
        - common

- hosts: vps, home_server
  name: VPS and Home Server Tasks
  roles:
    - role: docker
      tags:
        - docker

- hosts: vps
  name: VPS Tasks
  roles:
    - role: traefik
      tags:
        - traefik
    - role: wireguard-server
      tags:
        - wireguard-server

- hosts: home_server
  name: Home Server Tasks
  roles:
    - role: pihole
      tags:
        - pihole
    - role: traefik
      tags:
        - traefik
    - role: nextcloud
      tags:
        - nextcloud
    - role: scrutiny
      tags:
        - scrutiny
    - role: homeassistant
      tags:
        - homeassistant
    - role: transmission
      tags:
        - transmission
    - role: jellyfin
      tags:
        - jellyfin
    - role: jellyseerr
      tags:
        - jellyseerr
    - role: prowlarr
      tags:
        - prowlarr
    - role: radarr
      tags:
        - radarr
    - role: lidarr
      tags:
        - lidarr
    - role: sonarr
      tags:
        - sonarr
    - role: wireguard-client
      tags:
        - wireguard-client
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: homepage
      tags:
        - homepage
    - role: vaultwarden
      tags:
        - vaultwarden
