---
- hosts: vps, home_server
  name: Updating packages and installing docker
  strategy: linear
  roles:
    - role: common
      tags:
        - common
    - role: docker
      tags:
        - docker

- hosts: home_server
  name: Install Pihole in Home Server
  strategy: linear
  roles:
    - role: pihole
      tags:
        - pihole

- hosts: vps, home_server
  name: Install Traefik in vps and Home server
  strategy: free
  roles:
    - role: traefik
      tags:
        - traefik

- hosts: vps
  name: Install VPS's containers
  strategy: linear
  roles:
    - role: wireguard-server
      tags:
        - wireguard-server

- hosts: home_server
  name: Install Home Server's containers
  strategy: free
  roles:
    - role: homepage
      tags:
        - homepage
    - role: wireguard-client
      tags:
        - wireguard-client
    - role: nextcloud
      tags:
        - nextcloud
    - role: homeassistant
      tags:
        - homeassistant
    - role: jellyfin
      tags:
        - jellyfin
    - role: vaultwarden
      tags:
        - vaultwarden
    - role: transmission
      tags:
        - transmission
    - role: jellyseerr
      tags:
        - jellyseerr
    - role: prowlarr
      tags:
        - prowlarr
    - role: radarr
      tags:
        - radarr
    - role: lidarr
      tags:
        - lidarr
    - role: sonarr
      tags:
        - sonarr
    - role: bazarr
      tags:
        - bazarr
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: scrutiny
      tags:
        - scrutiny
