---
- hosts: vps, home_server
  name: Update packages and install docker
  strategy: linear
  roles:
    - role: common
      tags: common
    - role: geerlingguy.docker
      tags: docker
    - role: docker
      tags: docker

- hosts: vps
  name: Install VPS's containers
  strategy: linear
  roles:
    - role: traefik
      tags: traefik
    - role: wireguard-server
      tags: wireguard-server
    - role: headscale
      tags: headscale

- hosts: home_server
  name: Install Home Server's containers
  strategy: free
  roles:
    - role: homepage
    - role: immich
      tags: immich
    - role: wireguard-client
      tags: wireguard-client
    - role: tailscale
      tags: tailscale
    - role: nextcloud
      tags:
        - nextcloud
    - role: homeassistant
      tags:
        - homeassistant
    - role: jellyfin
      tags:
        - jellyfin
    - role: vaultwarden
      tags:
        - vaultwarden
    - role: transmission
      tags:
        - transmission
    - role: jellyseerr
      tags:
        - jellyseerr
    - role: prowlarr
      tags:
        - prowlarr
    - role: radarr
      tags:
        - radarr
    - role: lidarr
      tags:
        - lidarr
    - role: sonarr
      tags:
        - sonarr
    - role: bazarr
      tags:
        - bazarr
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: scrutiny
      tags:
        - scrutiny
    - role: openwebui
      tags: openwebui
