---
- hosts: all
  name: Common Tasks
  roles:
    - role: common
      tags:
        - always


- hosts: vps, home_server
  name: VPS and Home Server Tasks
  roles:
    - role: docker
      tags:
        - docker
    - role: traefik
      tags:
        - traefik

- hosts: vps
  name: VPS Tasks
  roles:
    # - role: wireguard
    #   tags:
    #     - wireguard
    # - role: headscale
    #   tags:
    #     - headscale
    - role: netmaker
      tags:
        - netmaker

- hosts: home_server
  name: Home Server Tasks
  roles:
    - role: pihole
      tags:
        - pihole
    - role: nextcloud
      tags:
        - nextcloud
    - role: scrutiny
      tags:
        - scrutiny
    - role: homeassistant
      tags:
        - homeassistant
    - role: transmission
      tags:
        - transmission
    - role: jellyfin
      tags:
        - jellyfin
    - role: jellyseerr
      tags:
        - jellyseerr
    - role: prowlarr
      tags:
        - prowlarr
    - role: radarr
      tags:
        - radarr
    - role: lidarr
      tags:
        - lidarr
    - role: sonarr
      tags:
        - sonarr
    - role: homarr
      tags:
        - homarr
    - role: dashdot
      tags:
        - dashdot
