---
- name: Create and run Jellyseerr container
  docker_container:
    image: "fallenbagel/jellyseerr:latest"
    name: "jellyseerr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/jellyseerr:/app/config"
    networks:
      - name: docker
    labels:
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.{{ domain }}`)
      traefik.http.routers.jellyseerr.entrypoints: https
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.services.jellyseerr.loadbalancer.server.port: "5055"
    restart_policy: unless-stopped

- name: Add CNAME entry for jellyseerr
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: jellyseerr
