---
- name: Create and run Jellyseerr container
  community.docker.docker_container:
    image: "fallenbagel/jellyseerr:latest"
    name: "jellyseerr"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/jellyseerr:/app/config"
    networks:
      - name: docker
    labels:
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.{{ domain_name }}`)
      traefik.http.routers.jellyseerr.entrypoints: https
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.services.jellyseerr.loadbalancer.server.port: "5055"

      homepage.name: "Jellyseerr"
      homepage.group: "Main Apps"
      homepage.href: "http://jellyseerr.{{ domain_name }}"
      homepage.description: "Interface for Media Requests"
      homepage.icon: "jellyseerr.png"
      # homepage.widget.type: jellyseerr
      # homepage.widget.url: "http://jellyseerr:5055"
      # homepage.widget.key: ""
    restart_policy: unless-stopped

- name: Add CNAME entry for jellyseerr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: jellyseerr
