---
- name: Create and run Lidarr container
  community.docker.docker_container:
    image: "lscr.io/linuxserver/lidarr"
    name: "lidarr"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/lidarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.lidarr.rule: Host(`lidarr.{{ domain_name }}`)
      traefik.http.routers.lidarr.entrypoints: https
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"

      homepage.name: "Lidarr"
      homepage.group: "Media Management"
      homepage.href: "http://lidarr.{{ domain_name }}"
      homepage.description: "Requester for Music"
      homepage.icon: "lidarr.png"
      # homepage.widget.type: lidarr
      # homepage.widget.url: "http://lidarr:8686"
      # homepage.widget.key: ""
    restart_policy: unless-stopped

- name: Add CNAME entry for lidarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: lidarr
