---
- name: Create and run Lidarr container
  docker_container:
    image: "lscr.io/linuxserver/lidarr"
    name: "lidarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/lidarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.lidarr.rule: Host(`lidarr.{{ domain }}`)
      traefik.http.routers.lidarr.entrypoints: https
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"
    restart_policy: unless-stopped

- name: Add CNAME entry for lidarr
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: lidarr
