---
- name: Create and run Wg-Easy container
  community.docker.docker_container:
    name: "wireguard"
    image: "weejewel/wg-easy"
    pull: "{{ pull_images }}"
    networks:
      - name: docker
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    env:
      WG_HOST: "{{ ansible_host }}"
      WG_ALLOWED_IPS: "10.8.0.0/24, {{ hostvars.home_server.ansible_facts.default_ipv4.network }}/{{ hostvars.home_server.ansible_facts.default_ipv4.prefix }}"
      WG_DEFAULT_DNS: "{{ hostvars.home_server.ansible_facts.default_ipv4.address }}"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_dir }}/wg-easy:/etc/wireguard"
    labels:
      traefik.http.routers.wireguard.rule: Host(`wireguard.{{ domain_name }}`)
      traefik.http.routers.wireguard.entrypoints: https
      traefik.http.routers.wireguard.tls: "true"
      traefik.http.services.wireguard.loadbalancer.server.port: "51821"
      traefik.http.routers.wireguard.middlewares: auth

      homepage.name: "Wireguard Server"
      homepage.group: "Main Apps"
      homepage.href: "http://wireguard.{{ domain_name }}"
      homepage.description: "Dashboard for wireguard VPN service"
      homepage.icon: "wireguard.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for wireguard
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: wireguard
