---
- name: Create and run Radarr container
  community.docker.docker_container:
    image: "lscr.io/linuxserver/radarr"
    name: "radarr"
    pull: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/radarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.radarr.rule: Host(`radarr.{{ domain_name }}`)
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.tls: "true"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

      homepage.name: "Radarr"
      homepage.group: "Media Management"
      homepage.href: "http://radarr.{{ domain_name }}"
      homepage.description: "Requester for Movies"
      homepage.icon: "radarr.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for radarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: radarr
