---
- name: Run barebones container for apikey extraction
  community.docker.docker_container:
    name: "radarr"
    image: "lscr.io/linuxserver/radarr"
    volumes:
      - "{{ docker_dir }}/radarr:/config"
    restart_policy: unless-stopped
    comparisons:
      "*": ignore
      volumes: allow_more_present

- name: Get ApiKey for radarr
  ansible.builtin.import_role:
    name: common
    tasks_from: get_apikey_arr_apps.yml
  vars:
    service: radarr
    config_file: config

- name: Recreate Radarr container with necessary configs
  community.docker.docker_container:
    name: "radarr"
    image: "lscr.io/linuxserver/radarr"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/radarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.radarr.rule: Host(`radarr.{{ domain_name }}`)
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.tls: "true"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

      homepage.name: "Radarr"
      homepage.group: "Media Management"
      homepage.href: "http://radarr.{{ domain_name }}"
      homepage.description: "Requester for Movies"
      homepage.icon: "radarr.png"
      homepage.ping: http://radarr:7878
      homepage.widget.type: radarr
      homepage.widget.url: "http://radarr:7878"
      homepage.widget.key: "{{ apikey }}"

- name: Add CNAME entry for radarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: radarr
