---
- name: Create and run Radarr container
  docker_container:
    image: "lscr.io/linuxserver/radarr"
    name: "radarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/radarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    ports:
      - "7878:7878"
    restart_policy: unless-stopped