---
- name: Create and run Radarr container
  docker_container:
    image: "lscr.io/linuxserver/radarr"
    name: "radarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/radarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.piholeradarr.rule: Host(`radarr.{{ domain }}`)
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.tls: "true"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
    restart_policy: unless-stopped
