---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/homepage"
    owner: "{{ ansible_user }}"
    state: directory
    group: 101
    mode: 0775

- name: Copy the docker.yaml file
  ansible.builtin.template:
    src: docker.yaml.j2
    dest: "{{ docker_dir }}/homepage/docker.yaml"
    group: 101
    mode: 0775

- name: Copy the services.yaml file
  ansible.builtin.template:
    src: services.yaml.j2
    dest: "{{ docker_dir }}/homepage/services.yaml"
    group: 101
    mode: 0775

- name: Copy the bookmarks.yaml file
  ansible.builtin.template:
    src: bookmarks.yaml.j2
    dest: "{{ docker_dir }}/homepage/bookmarks.yaml"
    group: 101
    mode: 0775

- name: Copy the settings.yaml file
  ansible.builtin.template:
    src: settings.yaml.j2
    dest: "{{ docker_dir }}/homepage/settings.yaml"
    group: 101
    mode: 0775

- name: Verify stats for "docker" network
  community.docker.docker_network_info:
    name: docker
  register: docker_net

- name: Create and run Homepage container
  community.docker.docker_container:
    image: "ghcr.io/benphelps/homepage:main"
    name: "homepage"
    pull: true
    restart: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/homepage:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: docker
    etc_hosts:
      host.docker.internal: "{{ docker_net.network.IPAM.Config[0].Gateway }}"
    labels:
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.rule: Host(`{{ domain_name }}`) || Host(`homepage.{{ domain_name }}`)
      traefik.http.routers.homepage.tls: "true"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"

    restart_policy: unless-stopped

- name: Add CNAME entry for homepage
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: homepage
