---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/homepage"
    owner: "{{ username }}"
    state: directory
    group: 101
    mode: 0775

- name: Copy the docker.yaml file
  ansible.builtin.template:
    src: docker.yaml.j2
    dest: "{{ docker_dir }}/homepage/docker.yaml"
    group: 101
    mode: 0775

- name: Copy the services.yaml file
  ansible.builtin.template:
    src: services.yaml.j2
    dest: "{{ docker_dir }}/homepage/services.yaml"
    group: 101
    mode: 0775

- name: Copy the bookmarks.yaml file
  ansible.builtin.template:
    src: bookmarks.yaml.j2
    dest: "{{ docker_dir }}/homepage/bookmarks.yaml"
    group: 101
    mode: 0775

- name: Create and run Homepage container
  docker_container:
    image: "ghcr.io/benphelps/homepage:latest"
    name: "homepage"
    restart: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/homepage:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: docker
    labels:
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.rule: Host(`{{ domain }}`) || Host(`homepage.{{ domain }}`)
      traefik.http.routers.homepage.tls: "true"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"

    restart_policy: unless-stopped

- name: Add CNAME entry for homepage
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: homepage
