---
- name: Create and run MariaDB container
  community.docker.docker_container:
    name: "mariadb"
    image: "lscr.io/linuxserver/mariadb"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/mariadb:/config"
    ports:
      - "3306:3306/tcp"
    restart_policy: unless-stopped

- name: Create and run Nextcloud container
  community.docker.docker_container:
    image: "lscr.io/linuxserver/nextcloud"
    name: "nextcloud"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/nextcloud:/config"
      - "/home/caio/nextcloud-data:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.{{ domain_name }}`)
      traefik.http.routers.nextcloud.entrypoints: https
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.services.nextcloud.loadbalancer.server.scheme: https
      traefik.http.services.nextcloud.loadbalancer.server.port: "443"

      homepage.name: "Nextcloud"
      homepage.group: "Main Apps"
      homepage.href: "http://nextcloud.{{ domain_name }}"
      homepage.description: "Personal Cloud Storage"
      homepage.icon: "nextcloud.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for nextcloud
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: nextcloud
