---
- name: Create and run Transmission container
  community.docker.docker_container:
    image: "lscr.io/linuxserver/transmission"
    name: "transmission"
    pull: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
      # "TRANSMISSION_WEB_HOME": "/combustion-release/"
      # "TRANSMISSION_WEB_HOME": "/transmission-web-control/"
      # "TRANSMISSION_WEB_HOME": "/kettu/"
      "TRANSMISSION_WEB_HOME": "/flood-for-transmission/"
      # "TRANSMISSION_WEB_HOME": "/transmissionic/"
    volumes:
      - "{{ docker_dir }}/transmission:/config"
      - "{{ media_dir }}/torrents:/data/torrents"
    networks:
      - name: docker
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    labels:
      traefik.http.routers.transmission.rule: Host(`transmission.{{ domain_name }}`)
      traefik.http.routers.transmission.entrypoints: https
      traefik.http.routers.transmission.tls: "true"
      traefik.http.services.transmission.loadbalancer.server.port: "9091"

      homepage.name: "Transmission"
      homepage.group: "Media Management"
      homepage.href: "http://transmission.{{ domain_name }}"
      homepage.description: "BitTorrent Client"
      homepage.icon: "transmission.png"
      homepage.widget.type: transmission
      homepage.widget.url: "http://transmission:9091"
    restart_policy: unless-stopped

- name: Add CNAME entry for transmission
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: transmission
