---
- name: Create and run Transmission container
  docker_container:
    image: "lscr.io/linuxserver/transmission"
    name: "transmission"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/transmission:/config"
      - "{{ media_dir }}/torrents:/data/torrents"
    networks:
      - name: docker
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    labels:
      traefik.http.routers.transmission.rule: Host(`transmission.{{ domain }}`)
      traefik.http.routers.transmission.entrypoints: https
      traefik.http.routers.transmission.tls: "true"
      traefik.http.services.transmission.loadbalancer.server.port: "9091"

      homepage.name: "Transmission"
      homepage.group: "Media Management"
      homepage.href: "http://transmission.{{ domain }}"
      homepage.description: "BitTorrent Client"
      homepage.icon: "transmission.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for transmission
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: transmission
