---
- name: Create and run scrutiny container
  docker_container:
    name: "scrutiny"
    image: "ghcr.io/analogj/scrutiny:master-omnibus"
    capabilities:
      - SYS_RAWIO
    volumes:
      - "/run/udev:/run/udev:ro"
      - "{{ docker_dir }}/scrutiny/web:/opt/scrutiny/config"
      - "{{ docker_dir }}/scrutiny/influxdb:/opt/scrutiny/influxdb"
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
    networks:
      - name: docker
    labels:
      traefik.http.routers.scrutiny.rule: Host(`scrutiny.{{ domain }}`)
      traefik.http.routers.scrutiny.entrypoints: https
      traefik.http.routers.scrutiny.tls: "true"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"

      homepage.name: "Scrutiny"
      homepage.group: "Monitoring Tools"
      homepage.href: "http://scrutiny.{{ domain }}"
      homepage.description: "Disk Health Monitoring"
      homepage.icon: "scrutiny.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for scrutiny
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: scrutiny
