---
- name: Create and run scrutiny container
  community.docker.docker_container:
    name: "scrutiny"
    image: "ghcr.io/analogj/scrutiny:master-omnibus"
    pull: "{{ pull_images }}"
    capabilities:
      - SYS_RAWIO
    volumes:
      - "/run/udev:/run/udev:ro"
      - "{{ docker_dir }}/scrutiny/web:/opt/scrutiny/config"
      - "{{ docker_dir }}/scrutiny/influxdb:/opt/scrutiny/influxdb"
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
    networks:
      - name: docker
    labels:
      traefik.http.routers.scrutiny.rule: Host(`scrutiny.{{ domain_name }}`)
      traefik.http.routers.scrutiny.entrypoints: https
      traefik.http.routers.scrutiny.tls: "true"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"

      homepage.name: "Scrutiny"
      homepage.group: "Monitoring Tools"
      homepage.href: "http://scrutiny.{{ domain_name }}"
      homepage.description: "Disk Health Monitoring"
      homepage.ping: http://scrutiny:8080
      homepage.icon: "scrutiny.png"
      homepage.widget.type: scrutiny
      homepage.widget.url: "http://scrutiny:8080"
    restart_policy: unless-stopped

- name: Add CNAME entry for scrutiny
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: scrutiny
