---
- name: Create and run scrutiny container
  docker_container:
    name: "scrutiny"
    image: "ghcr.io/analogj/scrutiny:master-omnibus"
    capabilities:
      - SYS_RAWIO
    volumes:
      - "/run/udev:/run/udev:ro"
      - "{{ docker_dir }}/scrutiny/web:/opt/scrutiny/config"
      - "{{ docker_dir }}/scrutiny/influxdb:/opt/scrutiny/influxdb"
    devices:
      - "/dev/sda"
      - "/dev/sdb"
    labels:
      traefik.http.routers.scrutiny.rule: Host(`scrutiny.{{ domain }}`)
      traefik.http.routers.scrutiny.entrypoints: https
      traefik.http.routers.scrutiny.tls: "true"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"
    restart_policy: unless-stopped
