---
- name: Run barebones container for apikey extraction
  community.docker.docker_container:
    name: "prowlarr"
    image: "lscr.io/linuxserver/prowlarr:develop"
    volumes:
      - "{{ docker_dir }}/prowlarr:/config"
    restart_policy: unless-stopped
    comparisons:
      "*": ignore
      volumes: allow_more_present

- name: Get ApiKey for prowlarr
  ansible.builtin.import_role:
    name: common
    tasks_from: get_apikey_arr_apps.yml
  vars:
    service: prowlarr

- name: Recreate Prowlarr container with necessary configs
  community.docker.docker_container:
    image: "lscr.io/linuxserver/prowlarr:develop"
    name: "prowlarr"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/prowlarr:/config"
    networks:
      - name: docker
    labels:
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.{{ domain_name }}`)
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"

      homepage.name: "Prowlarr"
      homepage.group: "Media Management"
      homepage.href: "http://prowlarr.{{ domain_name }}"
      homepage.description: "Indexer Manager for *arr apps"
      homepage.icon: "prowlarr.png"
      homepage.ping: http://prowlarr:9696/
      homepage.widget.type: prowlarr
      homepage.widget.url: "http://prowlarr:9696"
      homepage.widget.key: "{{ apikey }}"
    restart_policy: unless-stopped

- name: Add CNAME entry for prowlarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: prowlarr
