---
- name: Create and run Prowlarr container
  community.docker.docker_container:
    image: "lscr.io/linuxserver/prowlarr:develop"
    name: "prowlarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/prowlarr:/config"
    networks:
      - name: docker
    labels:
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.{{ domain }}`)
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"

      homepage.name: "Prowlarr"
      homepage.group: "Media Management"
      homepage.href: "http://prowlarr.{{ domain }}"
      homepage.description: "Indexer Manager for *arr apps"
      homepage.icon: "prowlarr.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for prowlarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: prowlarr
