---
- name: Create and run Vaultwarden container
  community.docker.docker_container:
    image: "vaultwarden/server:latest"
    name: "vaultwarden"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
      "ADMIN_TOKEN": "{{ vaultwarden_token }}"
    volumes:
      - "{{ docker_dir }}/vaultwarden:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.vaultwarden.rule: Host(`vaultwarden.{{ domain }}`)
      traefik.http.routers.vaultwarden.entrypoints: https
      traefik.http.routers.vaultwarden.tls: "true"
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"

      homepage.name: "Vaultwarden"
      homepage.group: "Main Apps"
      homepage.href: "http://vaultwarden.{{ domain }}/admin"
      homepage.description: "Bitwarden-based Password Manager"
      homepage.icon: "vaultwarden.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for vaultwarden
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: vaultwarden
