---
- name: Create and run Sonarr container
  docker_container:
    image: "lscr.io/linuxserver/sonarr"
    name: "sonarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/sonarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    ports:
      - "8989:8989"
    restart_policy: unless-stopped
