---
- name: Run barebones container for apikey extraction
  community.docker.docker_container:
    name: "sonarr"
    image: "lscr.io/linuxserver/sonarr"
    volumes:
      - "{{ docker_dir }}/sonarr:/config"
    restart_policy: unless-stopped
    comparisons:
      "*": ignore
      volumes: allow_more_present

- name: Get ApiKey for sonarr
  ansible.builtin.import_role:
    name: common
    tasks_from: get_apikey_arr_apps.yml
  vars:
    service: sonarr
    config_file: config

- name: Recreate Sonarr container with necessary configs
  community.docker.docker_container:
    image: "lscr.io/linuxserver/sonarr"
    name: "sonarr"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/sonarr:/config"
      - "{{ media_dir }}:/data"
    networks:
      - name: docker
    labels:
      traefik.http.routers.sonarr.rule: Host(`sonarr.{{ domain_name }}`)
      traefik.http.routers.sonarr.entrypoints: https
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"

      homepage.name: "Sonarr"
      homepage.group: "Media Management"
      homepage.href: "http://sonarr.{{ domain_name }}"
      homepage.description: "Requester for TV Shows"
      homepage.icon: "sonarr.png"
      homepage.ping: http://sonarr:8989/
      homepage.widget.type: sonarr
      homepage.widget.url: "http://sonarr:8989"
      homepage.widget.key: "{{ apikey }}"
    restart_policy: unless-stopped

- name: Add CNAME entry for sonarr
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: sonarr
