---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/prometheus"
    owner: "{{ ansible_user }}"
    state: directory
    group: 101
    mode: 0775

- name: Copy the prometheus.yml file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ docker_dir }}/prometheus/prometheus.yml"
    group: 101
    mode: 0775

- name: Create and run Prometheus container
  community.docker.docker_container:
    image: "prom/prometheus:latest"
    name: "prometheus"
    pull: "{{ pull_images }}"
    restart: true
    env:
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/prometheus:/etc/prometheus"
    networks:
      - name: docker
    labels:
      traefik.http.routers.prometheus.rule: Host(`prometheus.{{ domain_name }}`)
      traefik.http.routers.prometheus.entrypoints: https
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"

      homepage.name: "Prometheus"
      homepage.group: "Monitoring Tools"
      homepage.href: "http://prometheus.{{ domain_name }}"
      homepage.description: "Metrics-based Monitoring Tool"
      homepage.icon: "prometheus.png"
    restart_policy: unless-stopped

- name: Add CNAME entry for prometheus
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: prometheus
