---
- name: Create and run Homarr container
  docker_container:
    image: "ghcr.io/ajnart/homarr:latest"
    name: "homarr"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/homarr/config:/app/data/configs"
      - "{{ docker_dir }}/homarr/icons:/app/public/icons"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: docker
    labels:
      traefik.http.routers.homarr.entrypoints: https
      traefik.http.routers.homarr.rule: Host(`{{ domain }}`) || Host(`homarr.{{ domain }}`)
      traefik.http.routers.homarr.tls: "true"
      traefik.http.services.homarr.loadbalancer.server.port: "7575"
    restart_policy: unless-stopped

- name: Add CNAME entry for homarr
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: homarr
