---
- name: Install updates (Ubuntu)
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: ansible_distribution == "Ubuntu"
- name: Install updates (Arch Linux)
  become: true
  pacman:
    update_cache: true
    upgrade: true
  when: ansible_distribution == "Archlinux"
