---
- name: Set amd64 arch
  ansible.builtin.set_fact:
    repo_arch: amd64
  when: ansible_architecture == "x86_64"

- name: Set arm64 arch
  ansible.builtin.set_fact:
    repo_arch: arm64
  when: (ansible_architecture == "arm64") or (ansible_architecture == "aarch64")

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true

# - name: Ensure /etc/docker/ directory exists.
#   ansible.builtin.file:
#     path: /etc/docker
#     state: directory
#     mode: 0755

# - name: Configure Docker daemon options.
#   ansible.builtin.copy:
#     content: '{"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}'
#     dest: /etc/docker/daemon.json
#     mode: 0644
#   notify: Restart docker

- name: Chmod the data folder
  become: true
  ansible.builtin.file:
    dest: "{{ docker_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0775"
    group: "users"

- name: Create the docker network
  community.docker.docker_network:
    name: docker
