---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik"
    owner: "{{ ansible_user }}"
    state: directory
    group: 101
    mode: 0775

- name: Create the acme.json file
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik/acme.json"
    state: touch
    owner: "{{ ansible_user }}"
    group: 101
    mode: 0600

- name: Copy the traefik.yml file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ docker_dir }}/traefik/traefik.yml"
    group: 101
    mode: 0775

- name: Verify stats for "docker" network
  community.docker.docker_network_info:
    name: docker
  register: docker_net

- name: Create and run Traefik container
  community.docker.docker_container:
    image: "traefik:latest"
    name: "traefik"
    pull: true
    restart: true
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
      "DUCKDNS_TOKEN": "{{ duckdns_token }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/traefik/traefik.yml:/traefik.yml:ro"
      - "{{ docker_dir }}/traefik/acme.json:/acme.json"
    networks:
      - name: docker
    etc_hosts:
      host.docker.internal: "{{ docker_net.network.IPAM.Config[0].Gateway }}"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    labels:
      traefik.http.middlewares.auth.basicauth.users: "{{ auth_credentials }}"
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.rule: Host(`traefik.{{ domain_name }}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: duckdns
      traefik.http.routers.traefik.tls.domains[0].main: "{{ domain_name }}"
      traefik.http.routers.traefik.tls.domains[0].sans: "*.{{ domain_name }}"

      homepage.name: "Traefik"
      homepage.group: "Networks Tools"
      homepage.href: "http://traefik.{{ domain_name }}"
      homepage.description: "Reverse Proxy"
      homepage.icon: "traefik.png"
      # homepage.widget.type: traefik
      # homepage.widget.url: "http://traefik"
      # homepage.widget.username: ""
      # homepage.widget.password: ""

    restart_policy: unless-stopped

- name: Add CNAME entry for traefik
  ansible.builtin.import_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: traefik
