---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/headscale"
    recurse: true
    owner: "{{ username }}"
    group: 100
    mode: 0770

- name: Copy the headscale.yml file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ docker_dir }}/headscale/config.yaml"
    group: 100
    mode: 0770

- name: Create and run Headscale container
  docker_container:
    name: "headscale"
    image: "headscale/headscale:latest"
    restart: true
    networks:
      - name: docker
    ports:
      - "9090:9090"
    volumes:
      - "{{ docker_dir }}/headscale:/etc/headscale"
      - "{{ docker_dir }}/headscale/data:/var/lib/headscale"
    command: headscale serve
    labels:
      traefik.http.routers.headscale-vpn.entrypoints: https
      traefik.http.routers.headscale-vpn.rule: Host(`headscale.{{ domain }}`)
      traefik.http.routers.headscale-vpn.service: headscale-vpn
      traefik.http.services.headscale-vpn.loadbalancer.server.port: "8080"
    restart_policy: unless-stopped


- name: Create and run Headscale-UI container
  docker_container:
    name: "headscale-ui"
    image: "ghcr.io/gurucomputing/headscale-ui:latest"
    networks:
      - name: docker
    volumes:
      - "{{ docker_dir }}/headscale:/etc/headscale"
      - "{{ docker_dir }}/headscale/data:/var/lib/headscale"
    command: headscale serve
    labels:
      traefik.http.routers.headscale.entrypoints: https
      traefik.http.routers.headscale.rule: "Host(`headscale.{{ domain }}`)&& PathPrefix(`/web`)"
      traefik.http.routers.headscale.tls: "true"
      traefik.http.services.headscale.loadbalancer.server.scheme: https
      traefik.http.services.headscale.loadbalancer.server.port: "443"
      traefik.http.routers.headscale.middlewares: auth
    restart_policy: unless-stopped
