---

- name: Create and run Wireguard container
  docker_container:
    name: "wireguard"
    image: "weejewel/wg-easy"
    networks:
      - name: wg_network
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    state: "started"
    env:
      "WG_HOST": "{{ wireguard_host }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - "{{ docker_dir }}/wg-easy:/etc/wireguard"
    restart_policy: unless-stopped
