---

- name: Create and run Wireguard container
  docker_container:
    name: "wireguard"
    image: "weejewel/wg-easy"
    networks:
      - name: docker
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    env:
      WG_HOST: "{{ wireguard_host }}"
      WG_ALLOWED_IPS: "10.8.0.0/24, {{ wireguard_extra_allowed_ips }}"
      WG_DEFAULT_DNS: "{{ wireguard_dns }}"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_dir }}/wg-easy:/etc/wireguard"
    labels:
      traefik.http.routers.wireguard.rule: Host(`wireguard.{{ domain }}`)
      traefik.http.routers.wireguard.entrypoints: https
      traefik.http.routers.wireguard.tls: "true"
      traefik.http.services.wireguard.loadbalancer.server.port: "51821"
      traefik.http.routers.wireguard.middlewares: auth
    restart_policy: unless-stopped

- name: Add CNAME entry for wireguard
  ansible.builtin.include_role:
    name: pihole
    tasks_from: add_cname_record.yml
  vars:
    subdomain: wireguard
