---
- name: Add CNAME record for {{ subdomain }}
  ansible.builtin.lineinfile:
    insertafter: EOF
    line: "cname={{ subdomain }}.{{ domain }},{{ domain }}"
    path: "{{ docker_dir }}/pihole/dnsmasq.d/05-pihole-custom-cname.conf"
  when: cname_file is defined
