---
- name: Add CNAME record for {{ subdomain }}
  when: cname_file is defined
  ansible.builtin.lineinfile:
    insertafter: EOF
    line: "cname={{ subdomain }}.{{ domain_name }},{{ domain_name }}"
    path: "{{ docker_dir }}/pihole/dnsmasq.d/05-pihole-custom-cname.conf"
  notify: Restart pihole
