---
- name: Disable Stub listener in systemd-resolved
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Uncomment line in resolved.conf
      ansible.builtin.lineinfile:
        dest: /etc/systemd/resolved.conf
        regexp: '#DNSStubListener=yes'
        line: 'DNSStubListener=no'
    - name: Change /etc/resolv.conf symlink to /run/systemd/resolve/resolv.conf
      ansible.builtin.file:
        src: /etc/resolv.conf
        dest: /run/systemd/resolve/resolv.conf
        state: link
        force: true
    - name: Restart systemd-resolved service
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted

- name: Create the pihole folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/pihole/pihole"
    owner: "{{ ansible_user }}"
    recurse: true

- name: Create the dnsmasq.d folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/pihole/dnsmasq.d"
    owner: "{{ ansible_user }}"
    recurse: true

- name: Copy the custom.list file
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ docker_dir }}/pihole/pihole/custom.list"
    group: 101
    mode: 0775

- name: Create the 05-pihole-custom-cname.conf file
  ansible.builtin.file:
    state: touch
    dest: "{{ docker_dir }}/pihole/dnsmasq.d/05-pihole-custom-cname.conf"
    group: 101
    mode: 0775
  register: cname_file

- name: Create and run Pihole container
  community.docker.docker_container:
    image: "pihole/pihole:latest"
    name: "pihole"
    pull: "{{ pull_images }}"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/pihole/pihole:/etc/pihole"
      - "{{ docker_dir }}/pihole/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      - name: docker
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      traefik.http.routers.pihole.rule: Host(`pihole.{{ domain_name }}`)
      traefik.http.routers.pihole.entrypoints: https
      traefik.http.routers.pihole.tls: "true"
      traefik.http.services.pihole.loadbalancer.server.port: "80"

      homepage.name: "Pi-Hole"
      homepage.group: "Networks Tools"
      homepage.href: "http://pihole.{{ domain_name }}/admin"
      homepage.description: "DNS server with Ad-Blocking capabilities"
      homepage.icon: "pihole.png"
      homepage.widget.type: pihole
      homepage.widget.url: "http://pihole"

    restart_policy: unless-stopped

- name: Add CNAME entry for pihole
  ansible.builtin.import_tasks: add_cname_record.yml
  vars:
    subdomain: pihole
