---
- name: Create the pihole folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/pihole/pihole"
    owner: "{{ username }}"

- name: Create the dnsmasq.d folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/pihole/dnsmasq.d"
    owner: "{{ username }}"

- name: Copy the custom.list file
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ docker_dir }}/pihole/pihole/custom.list"
    group: 101
    mode: 0775

- name: Create the 05-pihole-custom-cname.conf file
  ansible.builtin.file:
    state: touch
    dest: "{{ docker_dir }}/pihole/dnsmasq.d/05-pihole-custom-cname.conf"
    group: 101
    mode: 0775
  register: cname_file

- name: Add CNAME entry for pihole
  ansible.builtin.import_tasks: add_cname_record.yml
  vars:
    subdomain: pihole

- name: Create and run Pihole container
  docker_container:
    image: "pihole/pihole:latest"
    name: "pihole"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "UMASK": "002"
      "TZ": "America/Sao_Paulo"
    volumes:
      - "{{ docker_dir }}/pihole/pihole:/etc/pihole"
      - "{{ docker_dir }}/pihole/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      - name: docker
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      traefik.http.routers.pihole.rule: Host(`pihole.{{ domain }}`)
      traefik.http.routers.pihole.entrypoints: https
      traefik.http.routers.pihole.tls: "true"
      traefik.http.services.pihole.loadbalancer.server.port: "80"
    restart_policy: unless-stopped
